### ISSUE TITLE
Internal Error when trying to use Editor Menu

### ISSUE THREAD

**Issue by WardenW7** [AdvancedPlugins/Jobs#25]
### Describe the bug

When trying to use /ajadmin editor (or any variation of the command) the server returns an Internal Error output with a ton of error messages in console. Tried it in a completely clean server as well, same errors.

`[16:39:27] [Server thread/INFO]: Khaosz issued server command: /ajadmin editor
[16:39:27] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ajadmin' in plugin AdvancedJobs v1.1.9
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1013) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:30) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:103) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:442) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:344) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:331) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2301) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$15(ServerGamePacketListenerImpl.java:2261) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1498) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1475) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1398) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1376) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.advancedplugins.jobs.impl.utils.nbt.backend.NBTReflectionUtil
	at net.advancedplugins.jobs.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:164) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.creator.gui.CreatorJobList.open(CreatorJobList.java:96) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.creator.GUICreatorHandler.openEditor(GUICreatorHandler.java:72) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.commands.jobsAdmin.QuestEditorSub.onExecute(QuestEditorSub.java:19) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.commands.jobsAdmin.QuestEditorSub.onExecute(QuestEditorSub.java:8) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.commands.Command.middleMan(Command.java:28) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.commands.CommandBase.onCommand(CommandBase.java:98) ~[AdvancedJobs-1.1.9(1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more
Caused by: java.lang.ExceptionInInitializerError: Exception net.advancedplugins.jobs.impl.utils.nbt.backend.NbtApiException: Exception while creating a new instance of 'null' [in thread "Server thread"]
	at net.advancedplugins.jobs.impl.utils.nbt.backend.ObjectCreator.getInstance(ObjectCreator.java:43) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.nbt.backend.NBTContainer.<init>(NBTContainer.java:23) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.nbt.backend.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:642) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.nbt.backend.NBTCompound.setString(NBTCompound.java:164) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.nbt.NBTapi.addNBTTag(NBTapi.java:15) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.creator.gui.CreatorJobList.open(CreatorJobList.java:96) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.creator.GUICreatorHandler.openEditor(GUICreatorHandler.java:78) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.commands.jobsAdmin.QuestEditorSub.onExecute(QuestEditorSub.java:19) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.commands.jobsAdmin.QuestEditorSub.onExecute(QuestEditorSub.java:8) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.commands.Command.middleMan(Command.java:28) ~[AdvancedJobs-1.1.9(1).jar:?]
	at net.advancedplugins.jobs.impl.utils.commands.CommandBase.onCommand(CommandBase.java:98) ~[AdvancedJobs-1.1.9(1).jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more`

### How to reproduce

Install plugin, try to run /ajadmin editor

**Comment by KPGTB** [comment]
Should be fixed in the latest version (1.2.0)
